[package]
name = "makexpstub"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
include_dir = "0.7.2"
goblin = "0.5"
scroll = "0.11"
clap = { version = "4.0.4", features = ["derive"] }
flexi_logger = "0.23"
log = "0.4"